name = "SlurmSubmission"
uuid = "369b147d-0ff1-469c-a749-0d8696e5fc26"
authors = ["James Gardner <james.gardner1421@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Term = "22787eb5-b846-44ae-b979-8e399b8463ab"

[compat]
Term = "0.2, 0.3, 1"
julia = "1.7, 1.8"
